pub fn vk_to_string(vk: u16) -> String {
    match vk {
        0x01 => "左クリック".to_string(),
        0x02 => "右クリック".to_string(),
        0x03 => "Control-break".to_string(),
        0x04 => "中クリック".to_string(),
        0x05 => "X1クリック".to_string(),
        0x06 => "X2クリック".to_string(),
        0x08 => "Backspace".to_string(),
        0x09 => "Tab".to_string(),
        0x0C => "Clear".to_string(),
        0x0D => "Enter".to_string(),
        0x10 => "Shift".to_string(),
        0x11 => "Ctrl".to_string(),
        0x12 => "Alt".to_string(),
        0x13 => "Pause".to_string(),
        0x14 => "Caps Lock".to_string(),
        0x15 => "Kana".to_string(),
        0x16 => "IME On".to_string(),
        0x17 => "Junja".to_string(),
        0x18 => "Final".to_string(),
        0x19 => "Hanja".to_string(),
        0x1A => "IME Off".to_string(),
        0x1B => "Esc".to_string(),
        0x1C => "変換".to_string(),
        0x1D => "無変換".to_string(),
        0x1E => "Accept".to_string(),
        0x1F => "Mode Change".to_string(),
        0x20 => "Space".to_string(),
        0x21 => "Page Up".to_string(),
        0x22 => "Page Down".to_string(),
        0x23 => "End".to_string(),
        0x24 => "Home".to_string(),
        0x25 => "Left Arrow".to_string(),
        0x26 => "Up Arrow".to_string(),
        0x27 => "Right Arrow".to_string(),
        0x28 => "Down Arrow".to_string(),
        0x29 => "Select".to_string(),
        0x2A => "Print".to_string(),
        0x2B => "Execute".to_string(),
        0x2C => "Print Screen".to_string(),
        0x2D => "Insert".to_string(),
        0x2E => "Delete".to_string(),
        0x2F => "Help".to_string(),
        0x30..=0x39 => format!("{}", (vk - 0x30) as u8),
        0x41..=0x5A => format!("{}", ((vk - 0x41) as u8 + b'A') as char),
        0x5B => "左Win".to_string(),
        0x5C => "右Win".to_string(),
        0x5D => "Applications".to_string(),
        0x5F => "Sleep".to_string(),
        0x60..=0x69 => format!("Numpad {}", vk - 0x60),
        0x6A => "Numpad *".to_string(),
        0x6B => "Numpad +".to_string(),
        0x6C => "Numpad Separator".to_string(),
        0x6D => "Numpad -".to_string(),
        0x6E => "Numpad .".to_string(),
        0x6F => "Numpad /".to_string(),
        0x70..=0x87 => format!("F{}", vk - 0x70 + 1),
        0x90 => "Num Lock".to_string(),
        0x91 => "Scroll Lock".to_string(),
        0xA0 => "左Shift".to_string(),
        0xA1 => "右Shift".to_string(),
        0xA2 => "左Ctrl".to_string(),
        0xA3 => "右Ctrl".to_string(),
        0xA4 => "左Alt".to_string(),
        0xA5 => "右Alt".to_string(),
        0xBA => "OEM 1".to_string(),
        0xBB => "OEM +".to_string(),
        0xBC => "OEM ,".to_string(),
        0xBD => "OEM -".to_string(),
        0xBE => "OEM .".to_string(),
        0xBF => "OEM 2".to_string(),
        0xC0 => "OEM 3".to_string(),
        0xDB => "OEM 4".to_string(),
        0xDC => "OEM 5".to_string(),
        0xDD => "OEM 6".to_string(),
        0xDE => "OEM 7".to_string(),
        0xDF => "OEM 8".to_string(),
        0xE2 => "OEM 102".to_string(),
        0xE5 => "IME Process".to_string(),
        0xE7 => "Packet".to_string(),
        0xF6 => "Attn".to_string(),
        0xF7 => "CrSel".to_string(),
        0xF8 => "ExSel".to_string(),
        0xF9 => "Erase EOF".to_string(),
        0xFA => "Play".to_string(),
        0xFB => "Zoom".to_string(),
        0xFC => "NoName".to_string(),
        0xFD => "PA1".to_string(),
        0xFE => "OEM Clear".to_string(),
        _ => format!("VK_{}", vk),
    }
}

pub fn string_to_vk(s: &str) -> u16 {
    for vk in 8..=254 {
        if vk_to_string(vk).eq_ignore_ascii_case(s) {
            return vk;
        }
    }
    0
}
